# Port 80 is for dehydrated/letsencrypt
server {
  listen 80;
  listen [::]:80;
  server_name act-ldmx-mon2.cern-test.uiocloud.no;

  location /.well-known/acme-challenge {
  alias /var/www/dehydrated;
  }
 
  # redirect all other requests to SSL
  return 301 https://$host$request_uri;
}

